language: node_js
node_js:
  - '10'
env:
  - CI=true

git:
  depth: 5
    
addons:
  sonarcloud:
    organization: "acao-github" # the key of the org you chose at step #3
script:
  - yarn lint && yarn coverage -- --runInBand --no-cache && yarn size
  # other script steps might be done before running the actual analysis
  - sonar-scanner